# Generated by Django 5.2.7 on 2025-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='otp_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
