# Generated by Django 5.2.7 on 2025-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userauth_otp_userauth_otp_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
