# Generated by Django 5.2.7 on 2025-10-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userauth_default_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='default_delivery_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
