# Generated by Django 5.2.7 on 2025-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userauth_default_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userauth',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
