# Generated by Django 5.2.7 on 2025-10-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userauth_average_rating_userauth_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
