# Generated by Django 5.2.7 on 2025-10-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userauth_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='wallet',
        ),
    ]
