# Generated by Django 5.2.7 on 2025-10-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userauth_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='location_latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userauth',
            name='location_longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
