# Generated by Django 5.2.7 on 2025-10-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userauth_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
