# Generated by Django 5.2.7 on 2025-10-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userauth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
