# Generated by Django 5.2.7 on 2025-10-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userauth_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
