# Generated by Django 5.2.7 on 2025-10-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userauth_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
