# Generated by Django 5.2.7 on 2025-10-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userauth_login_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
