# Generated by Django 5.2.7 on 2025-10-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to='chat/'),
        ),
    ]
