# Generated by Django 5.2.7 on 2025-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'confirmed'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
