# Generated by Django 5.2.7 on 2025-10-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0004_alter_deliveryrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_location_latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_location_longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
