# Generated by Django 5.2.7 on 2025-10-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_deliveryrequest_delivery_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='delivery_location_latitude',
            new_name='delivery_location_lat_long',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='delivery_location_longitude',
            new_name='pickup_location_lat_long',
        ),
    ]
