# Generated by Django 5.2.7 on 2025-10-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_rename_delivery_location_latitude_deliveryrequest_delivery_location_lat_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='delivery_location_lat_long',
            new_name='delivery_location_lat',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='pickup_location_lat_long',
            new_name='delivery_location_long',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_location_lat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_location_long',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
