# Generated by Django 5.2.7 on 2025-10-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0007_rename_delivery_location_lat_long_deliveryrequest_delivery_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
