# Generated by Django 5.2.7 on 2025-10-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0008_deliveryrequest_distance_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='actual_delivery_time',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='expected_delivery_time',
        ),
    ]
